### ISSUE TITLE
socialregistration_facebookprofile reference to django-site causes an error

### ISSUE THREAD

**Issue by kkamalov** [flashingpumpkin/django-socialregistration#139]
i was writing some unit tests for my django application and got this issue:

Hint: Look at the output of 'django-admin.py sqlflush'. That's the SQL this command wasn't able to run.
The full error: cannot truncate a table referenced in a foreign key constraint
DETAIL:  Table "socialregistration_facebookprofile" references "django_site".
HINT:  Truncate table "socialregistration_facebookprofile" at the same time, or use TRUNCATE ... CASCADE.

does anyone know how to solve it?

thanks,

**Comment by flashingpumpkin** [comment]
Do you have full tracebacks of your unit tests?

**Comment by carmelly** [comment]
I think this is related to #148. Back in commit 1d54e51, the FacebookProfile and FacebookAccessToken models were moved from socialregistration/models.py to socialregistration/contrib/facebook/models.py but there's no migration to rename the tables.

**Comment by flashingpumpkin** [comment]
Hi

There indeed isn't. The issue is that I did quite a rewrite when going from v0.4.x to v0.5.x and figured it would be nice to break the different consumers out into their own little apps making it easier to pick specific features and compose your projects that way. Eg, when just using the Facebook parts you won't get the Twitter tables.

So. How to migrate? 

The easiest way is to swap v0.4.x out for v0.5.x and run `syncdb` db normally. That'll create the `facebook` table and not touch the old `socialregistration_*` tables. Once that is done, you'll have to write a [datamigration](http://south.readthedocs.org/en/latest/tutorial/part3.html) along the following lines to get everything from the old table into the new models:

``` python
from socialregistration.contrib.facebook.models import FacebookProfile, FacebookAccessToken
from django.db import connection 

cursor = connection.cursor()
cursor.execute("SELECT * FROM socialregistration_facebookprofile")
profiles = cursor.fetchall()

for (pk, user_id, site_id, uid) in profiles:
    cursor.execute("SELECT * FROM socialregistration_facebookaccesstoken WHERE profile_id='{0}'".format(pk))
    (tpk, profile_id, access_token)  = cursor.fetchone()

    profile = FacebookProfile(pk = pk, uid = uid)
    profile.user_id = userid 
    profile.site_id = site_id
    profile.save()

    token = FacebookAccessToken(profile = profile, access_token = access_token)
    token.save()
```

**Note:**  I'm not sure if the table names are correct, don't run this on your live site but test it first. ;)

I hope that helps.

**Comment by jaddison** [comment]
Based on the example flashingpumpkin provided, this is what I had to do to get things working all right for me.  I'm still in the midst of testing it, but it appears fine so far.  I created a south datamigration to do this.

``` python
        cursor = connection.cursor()
        cursor.execute("SELECT id, user_id, uid, site_id FROM socialregistration_facebookprofile")
        profiles = cursor.fetchall()

        for (pk, user_id, uid, site_id) in profiles:
            user = get_object_or_None(User, pk=user_id)
            if user:
                profile, created = FacebookProfile.objects.get_or_create(uid = uid, user=user, site=Site.objects.get_current())

                cursor.execute("SELECT id, profile_id, access_token FROM socialregistration_facebookaccesstoken WHERE profile_id='{0}'".format(pk))
                tmp = cursor.fetchone()
                if tmp:
                    (tpk, profile_id, access_token)  = tmp
                    FacebookAccessToken.objects.get_or_create(profile = profile, access_token = access_token)

        cursor.execute("drop table socialregistration_facebookaccesstoken;")
        cursor.execute("drop table socialregistration_facebookprofile;")
        cursor.execute("drop table socialregistration_linkedinaccesstoken;")
        cursor.execute("drop table socialregistration_linkedinrequesttoken;")
        cursor.execute("drop table socialregistration_linkedinprofile;")
        cursor.execute("drop table socialregistration_twitterrequesttoken;")
        cursor.execute("drop table socialregistration_twitteraccesstoken;")
        cursor.execute("drop table socialregistration_twitterprofile;")
        cursor.execute("drop table socialregistration_openidstore;")
        cursor.execute("drop table socialregistration_openidnonce;")
        cursor.execute("drop table socialregistration_openidprofile;")
```

Notice that I only cared about the Facebook related data.  I deleted the old tables because due to foreign key constraints in the DB (postgresql for me), you are unable to delete a User object for example due to cascading references or something like that.  ;)

**Comment by flashingpumpkin** [comment]
Nice one. I think I'll add that to the docs as well.
