### ISSUE TITLE
facebook python sdk deprication

### ISSUE THREAD

**Issue by willcadell** [flashingpumpkin/django-socialregistration#146]
I saw the deprication notice on this:

https://github.com/facebook/python-sdk

do i need to be worried?

thanks for the great app!

w

**Comment by flashingpumpkin** [comment]
Hi

Facebook did indeed already take down the python-sdk once so I forked it to my account. ([facebook-sdk-fork](https://github.com/flashingpumpkin/facebook-sdk-fork))

In any case, the Python library does not do anything important anymore since I switched socialreg to use the server side OAuth flow. It's now only used to access the API from `request.facebook` if there's an access token - but not to authenticate / connect. The idea is to kick it out some time soon though.

Alen

**Comment by willcadell** [comment]
thanks!
