### ISSUE TITLE
How to retrieve email in openid and facebook?

### ISSUE THREAD

**Issue by vallettea** [flashingpumpkin/django-socialregistration#46]
I would really appreciate that someone tell me how it is possible to retrieve the email from the provider. I really don't know where to start (no documentation about this)
thanks

**Comment by flashingpumpkin** [comment]
I recommend you look up the documentation for those APIs to find out how to interact with them in more depth. socialregistration only provides methods to authenticate against the APIs and nothing more.

**Comment by vallettea** [comment]
ok, thanks
but i have another question:
what is the use of the profiles created by socialregistration?

**Comment by vallettea** [comment]
ok with your answer but since the autorization to retrieve informtion such as email address or picture is asked during the authentication, you should explain once for all how to interact with socialregistration to obtain thse authorizations.
thx

**Comment by flashingpumpkin** [comment]
Easiest way is to extend/decorate the classes that interact with the APIs.

Another way would be to override the urls to point at your own views that perform additional operations.

**Comment by alinebee** [comment]
I think the cleanest way to do this would be to duplicate django-socialregistration's auth.py into your own app/project, and decorate the User instance that is returned by the authenticate() methods. Then, change your AUTHENTICATION_BACKENDS setting to point to your own versions of the auth classes instead of django-socialregistration's. This way you can leave django-socialregistration itself completely untouched.

_EDIT: on further investigation, retrieving user data from the Facebook API (and probably all others) requires request-specific information that is unavailable to the authenticate() methods. So deeper customization would still be needed._

**Comment by jaylett** [comment]
If you have the FacebookMiddleware running, you can do something like:

```
facebook = request.facebook
obj = facebook.graph.get_object(facebook.uid)
email = obj.get(u'email', u'')
```

**Comment by flashingpumpkin** [comment]
You can now use the provided signals to retrieve additional user data. The signals provide 
- The user object
- The profile object
- The client object
